local mock = require("tests.mocks.factorio")

describe("cache", function()
  local cache

  before_each(function()
    mock.fresh()
    cache = require("scripts.cache")
  end)

  describe("new()", function()
    it("creates a cache with default generator", function()
      local c = cache.new()
      -- Default generator returns the key itself
      assert.are.equal("foo", c:get("foo"))
    end)

    it("creates a cache with custom generator", function()
      local c = cache.new(function(key) return key .. "!" end)
      assert.are.equal("bar!", c:get("bar"))
    end)
  end)

  describe("get()", function()
    it("returns nil for nil key", function()
      local c = cache.new()
      assert.is_nil(c:get(nil))
    end)

    it("generates and caches on first access", function()
      local calls = 0
      local c = cache.new(function(key)
        calls = calls + 1
        return string.upper(key)
      end)
      assert.are.equal("ABC", c:get("abc"))
      assert.are.equal("ABC", c:get("abc"))
      assert.are.equal(1, calls) -- generator called only once
    end)

    it("passes extra args to generator", function()
      local c = cache.new(function(key, suffix)
        return key .. (suffix or "")
      end)
      assert.are.equal("foo-bar", c:get("foo", "-bar"))
    end)
  end)

  describe("set() / has() / remove()", function()
    it("manually sets and retrieves a value", function()
      local c = cache.new()
      c:set("x", 42)
      assert.is_true(c:has("x"))
      assert.are.equal(42, c:get("x"))
    end)

    it("ignores set with nil key", function()
      local c = cache.new()
      c:set(nil, 99)
      assert.are.equal(0, c:size())
    end)

    it("removes an entry", function()
      local c = cache.new()
      c:set("a", 1)
      c:remove("a")
      assert.is_false(c:has("a"))
    end)
  end)

  describe("clear()", function()
    it("removes all entries", function()
      local c = cache.new()
      c:set("a", 1)
      c:set("b", 2)
      c:clear()
      assert.are.equal(0, c:size())
    end)
  end)

  describe("size() and keys()", function()
    it("reports correct size", function()
      local c = cache.new()
      assert.are.equal(0, c:size())
      c:set("a", 1)
      c:set("b", 2)
      assert.are.equal(2, c:size())
    end)

    it("returns all keys", function()
      local c = cache.new()
      c:set("x", 10)
      c:set("y", 20)
      local keys = c:keys()
      table.sort(keys)
      assert.are.same({"x", "y"}, keys)
    end)
  end)
end)
