data:extend{
  {
    type = "sprite",
    name = "li_pause",
    filename = "__logistics-insights__/graphics/pause-button.png",
    size = 64,
    scale = 1.0,
    flags = {"icon"},
  },
  {
    type = "sprite",
    name = "li_play",
    filename = "__logistics-insights__/graphics/play-button.png",
    size = 128,
    scale = 1.0,
    flags = {"icon"},
  },
  {
    type = "sprite",
    name = "li_step",
    filename = "__logistics-insights__/graphics/step-button.png",
    size = 64,
    scale = 1.0,
    flags = {"icon"},
  },
  {
    type = "sprite",
    name = "li_list",
    filename = "__logistics-insights__/graphics/list-button.png",
    size = 64,
    scale = 1.0,
    flags = {"icon"},
  },
  {
    type = "sprite",
    name = "li_pause_white",
    filename = "__logistics-insights__/graphics/pause-button-white.png",
    size = 64,
    scale = 1.0,
    flags = {"icon"},
  },
  {
    type = "sprite",
    name = "li_play_white",
    filename = "__logistics-insights__/graphics/play-button-white.png",
    size = 128,
    scale = 1.0,
    flags = {"icon"},
  },
  {
    type = "sprite",
    name = "li_step_white",
    filename = "__logistics-insights__/graphics/step-button-white.png",
    size = 128,
    scale = 1.0,
    flags = {"icon"},
  },
  {
    type = "sprite",
    name = "li_arrow",
    filename = "__logistics-insights__/graphics/arrow.png",
    size = 64,
    scale = 1.0,
    flags = {"gui-icon"},
  },
  {
    type = "sprite",
    name = "li_undersupply",
    filename = "__logistics-insights__/graphics/undersupply-icon.png",
    size = 64,
    scale = 1.0,
    flags = {"gui-icon"},
  },
  {
    type = "sprite",
    name = "li_suggestions",
    filename = "__logistics-insights__/graphics/suggestions-icon.png",
    size = 128,
    scale = 1.0,
    flags = {"gui-icon"},
  },
  {
    type = "sprite",
    name = "li_suggestions_centered",
    filename = "__logistics-insights__/graphics/suggestions-icon-centered.png",
    size = 128,
    scale = 1.0,
    flags = {"gui-icon"},
  }
}